-- --------------------------------------------------------------------------
-- Table gift_certificate
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gift_certificate(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                character varying(30),
    description         character varying(200),
    price               DECIMAL(5, 2),
    duration            integer,
    create_date         timestamp without time zone,
    last_update_date    timestamp without time zone
);

-- --------------------------------------------------------------------------
-- Table tag
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tag(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                character varying
);

-- --------------------------------------------------------------------------
-- Table gift_certificate_tag
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gift_certificate_tag(
    gift_certificate_id   bigint REFERENCES gift_certificate (id),
    tag_id                bigint REFERENCES tag (id),
    PRIMARY KEY (gift_certificate_id, tag_id)
);

COMMIT;
